name: Gizli Repo Domain Güncelleme

on:
  push:
    paths:
      - dizigom.txt
  workflow_dispatch:

jobs:
  trigger-private:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger private repo workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_TOKEN }}           # Private repo’ya erişim izni olan token
          repository: zerodayip/dizigom           # Private repo
          event-type: trigger-domain-workflow      # Private repo’da dinlenecek event type
          client-payload: '{"source":"public-repo"}'
