name: Gizli Repo Domain GÃ¼ncelleme

on:
  workflow_dispatch:

jobs:
  trigger-private:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger private repo 1 workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: zerodayip/dizigom
          event-type: trigger-domain-workflow
          client-payload: '{"source":"public-repo"}'

      - name: Trigger private repo 2 workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: zerodayip/diziyo
          event-type: trigger-domain-workflow
          client-payload: '{"source":"public-repo"}'

      - name: Trigger private repo 3 workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: zerodayip/anizm
          event-type: trigger-domain-workflow
          client-payload: '{"source":"public-repo"}'

      - name: Trigger private repo 4 workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: zerodayip/animenosub
          event-type: trigger-domain-workflow
          client-payload: '{"source":"public-repo"}'


